// creating api for items to show in web application

const product = [
  {
    id: 1,
    title: "T-shirt",
    image: "/assets/men2.webp",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "men's wear",
    price: "245",
  },
  {
    id: 2,
    title: "Women's Top",
    image: "/assets/women.jpg",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "woman's wear",
    price: "299",
  },
  {
    id: 3,
    title: "Men's Shirt",
    image: "/assets/men1.jpg",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "men's wear",
    price: "399",
  },
  {
    id: 4,
    title: "Women's Top",
    image: "/assets/women5.jpg",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "woman's wear",
    price: "199",
  },
  {
    id: 5,
    title: "Jewellery",
    image: "/assets/jwlry6.webp",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "jewellery",
    price: "499",
  },
  {
    id: 6,
    title: "Headphones",
    image: "/assets/electronic4.webp",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "electronic",
    price: "299",
  },
  {
    id: 7,
    title: "Watch",
    image: "/assets/electronic1.jpg",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "electronic",
    price: "999",
  },
  {
    id: 8,
    title: "Headphones",
    image: "/assets/electronic.jpg",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "electronic",
    price: "799",
  },
  ,
  {
    id: 9,
    title: "Jwelery",
    image: "/assets/jwlry3.webp",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "jewellery",
    price: "899",
  },
  {
    id: 10,
    title: "Women's Top",
    image: "/assets/women1.jpg",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "woman's wear",
    price: "399",
  },
  {
    id: 11,
    title: "Electronic",
    image: "/assets/electronic2.png",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "electronic",
    price: "299",
  },
  {
    id: 12,
    title: "Tshirt",
    image: "/assets/jwlry4.jpg",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "jewellery",
    price: "1999",
  },
  {
    id: 13,
    title: "Women's Top",
    image: "/assets/women4.jpg",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "woman's wear",
    price: "449",
  },
  {
    id: 14,
    title: "Men's Shirt",
    image: "/assets/jwlry6.webp",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "jewellery",
    price: "249",
  },
  {
    id: 15,
    title: "Men's Shirt",
    image: "/assets/men3.jpg",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "men's wear",
    price: "399",
  },
  {
    id: 16,
    title: "Men's Shirt",
    image: "/assets/men4.webp",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "men's wear",
    price: "1299",
  },
  {
    id: 17,
    title: "Men's Shirt",
    image: "/assets/mean1.jpg",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "men's wear",
    price: "999",
  },
  {
    id: 18,
    title: "Women's Top",
    image: "/assets/women6.jpg",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "woman's wear",
    price: "199",
  },
  {
    id: 19,
    title: "Men's Shirt",
    image: "/assets/jwlry4.jpg",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "jewellery",
    price: "1999",
  },
  {
    id: 20,
    title: "Electronic",
    image: "/assets/electronic5.webp",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "electronic",
    price: "2999",
  },
  {
    id: 21,
    title: "Electronic",
    image: "/assets/jwlry2.jpg",
    desc: "A quality product must be aesthetically pleasing as well as practical",
    category: "jewellery",
    price: "1199",
  },
];

export default product;
